Update dates for future community calls
dapr/community pull request #216
Opened 2022-09-07 16:11 UTC by nyemade-uversky

Signed-off-by: nyemade-uversky <55847877+nyemade-uversky@users.noreply.github.com>

2022-09-07 19:06 UTC, artursouza requested changes

2022-09-07 19:06 UTC, artursouza commented on README.md
> +- Wednesday Nov 2<sup>th</sup> 9:00am Pacific Time (PST) - [See it in your local time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20221019T09&p1=234&msg=Dapr+Community+Call)
You forgot to update the date inside the URL too.

2022-09-07 19:06 UTC, artursouza commented on README.md
> +- Wednesday Nov 16<sup>th</sup> 9:00am Pacific Time (PST) - [See it in your local time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20221019T09&p1=234&msg=Dapr+Community+Call)
Same.

2022-09-21 04:32 UTC, yaron2 approved these changes

2022-09-21 04:32 UTC, merged